#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBE793007AD22DF7E (tsujan2000@gmail.com)
#
Name     : lxqt-admin
Version  : 1.0.0
Release  : 9
URL      : https://github.com/lxqt/lxqt-admin/releases/download/1.0.0/lxqt-admin-1.0.0.tar.xz
Source0  : https://github.com/lxqt/lxqt-admin/releases/download/1.0.0/lxqt-admin-1.0.0.tar.xz
Source1  : https://github.com/lxqt/lxqt-admin/releases/download/1.0.0/lxqt-admin-1.0.0.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kwindowsystem-dev
BuildRequires : liblxqt-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libsystemd)
BuildRequires : polkit-qt
BuildRequires : qtbase-dev

%description
# lxqt-admin
## Overview
This repository provides two GUI tools to adjust settings of the operating system LXQt
is running on.

%prep
%setup -q -n lxqt-admin-1.0.0
cd %{_builddir}/lxqt-admin-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636132264
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1636132264
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lxqt-admin
cp %{_builddir}/lxqt-admin-1.0.0/COPYING %{buildroot}/usr/share/package-licenses/lxqt-admin/7fab4cd4eb7f499d60fe183607f046484acd6e2d
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
